name: auto-merge-astap-mirror
run-name: Merge ASTAP auto Pull Request
on:
  #push:
  #  branches: [ tmp ]
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:
    inputs:
      forced:
        description: 'Force merge without time checking?'
        required: false
        default: 'false'
jobs:
  auto-merge:
    runs-on: self-hosted
    container:
      image: ghcr.io/puppeteer/puppeteer:latest
      options: --user root
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: git-repo
      - name: Install prerequises
        run: yarn
        working-directory: git-repo/.github/workflows/ASTAP-scripts
      - name: Build
        run: yarn build
        working-directory: git-repo/.github/workflows/ASTAP-scripts
      - name: Launch AutoMerge script
        run: yarn start autoMerge ${{ github.event.inputs.forced == 'true' }} false -t ${{ secrets.GITHUB_TOKEN }}
        working-directory: git-repo/.github/workflows/ASTAP-scripts
